### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by WeersProductions**
Instead of a Unity project structure, which is only useful if the user is using it as the base of their project, move it to a submodule structure.

Users will use `git submodule` to clone the BulletSharpUnity3D repo in their own project. This also allows them to easily keep their submodule up-to-date with master, or to create a pull-request from their own changes.

I think this change is required to improve the overal usefulness of the wrapper.

### CODE REVIEW

**Comment by Phong13** [comment]
Thanks for sending the pull request.

I have a question about the Plugins folder. There can be only one Plugins folder per project and it must be an immediate child of Assets. As such, if a user wanted to check this out as a sub-module would the Plugins folder be owned by the BulletUnity submodule?

**Comment by Phong13** [comment]
BTW: I added the change that should fix the timing issues with FixedUpdate. Every Unity fixed update should match exactly one Bullet fixed update.

**Comment by WeersProductions** [comment]
About the Plugins folder:
That's a good point. Initially, I was thinking that was the way to go. 

The following [thread](https://forum.unity.com/threads/where-to-install-your-assets-for-scripting-packages-editor-extensions.292674/page-2) is discussing this in more detail. While a 'Plugins' subfolder under BulletSharp is way easier for both users as us (developers), the compile time will increase. We can fix this compile time by using [Assembly definitions](https://blogs.unity3d.com/2017/11/22/unity-2017-3b-feature-preview-assembly-definition-files-and-transform-tool/). I think that's the way to go.
I haven't tested this or tried this yet. I'll give it a shot when I find some time. 

About FixedUpdate:
Great! I already noticed, this branch is up-to-date with Master (and thus your latest commit).

I have more features locally that I want to push, but I'd like to have the structure of the project clear first.

**Comment by WeersProductions** [comment]
While it is true that BulletUnity won't take control of the Plugins folder if we put instructions in there to manually copy it over, it would add another step where people could make mistakes. I don't think we should do that. I think those that have multiple submodules and want to control multiple, know what they're doing. 

I'll report back about the Assembly Definition files and hope they're the solution!

For testing, is it enough for me to test whether everything still works on MacOS (and Windows) in editor and Build? I assume if it works for those, it will work for the other existing platforms as well, right?

**Comment by Phong13** [comment]
> While it is true that BulletUnity won't take control of the Plugins folder if we put instructions in there to manually copy it over, it would add another step where people could make mistakes. I don't think we should do that. I think those that have multiple submodules and want to control multiple, know what they're doing.
> 
> I'll report back about the Assembly Definition files and hope they're the solution!
> 
> For testing, is it enough for me to test whether everything still works on MacOS (and Windows) in editor and Build? I assume if it works for those, it will work for the other existing platforms as well, right?

I think you are correct about multiple submodules. If there is a class about who owns the plugins folder then they can checkout to a separate directory and copy over, or checkout the Plugins/BulletSharp instead of Plugins submodule.

For the Restructure that should be enough. If you change things in the BulletSharp API then you will need to test on all platforms.

**Comment by WeersProductions** [comment]
Good news! Assembly Definition files seem to be the way to go. I've tested it on OSX, standalone + editor. I'll test Windows coming week, but I don't think that will give any issues.
The .rsp file is not required anymore, since 'unsafe code' is defined in the Assembly Definition file. 

I think the structure is correct now, but any feedback is welcome! When we are going to use this structure, I will add a little 'Quick start' in the readme on how to add it as a submodule to your existing project.

**Comment by Phong13** [comment]
Sorry for being out of touch for a few days. This looks good. I tested it in 2017.1 and it works. Nice work.

**Pull request merged**
