### PR TITLE
Adding Threading capabilities to bullet

### PR DESCRIPTION
**Pull request by flonou**
Adding Threading capabilities to bullet. We needed this on a project where the physics engine had to run at a higher rate than what unity can do

### CODE REVIEW

**Comment by flonou** [comment]
Note : I'm not completely sure this is not breaking synchronization/interpolation in non-threaded mode

**Comment by Phong13** [comment]
Thanks for submitting this, this looks great!

Sorry for being so slow to review this. I have been swamped with work this past week. This is very interesting. There is a lot of code here so it will take me a little while to look it over.

**Comment by Phong13** [comment]
What version of Unity are you using?

**Comment by flonou** [comment]
Hi,
No rush for this, I had time to refine it a bit (and I still am, I might have found a more precise way of scheduling the thread). This was done on 2018.3 I think it requires .net4 is that ok for you? I can adapt the code for .net 3.5

**Comment by Phong13** [comment]
No 2018.3 is good. IMO it is OK not to support very old versions with this.

**Comment by WeersProductions** [comment]
I agree with you. We could even pin the last commit as a release and make
this a new version.

**Pull request merged**
